### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by MiTereKun** [Geograph-us/Cloud-Mail.Ru-Downloader#1]
проверили 3 раза, я и мой друг - у него там вовсе пусть к загрузчику не подошёл, а у меня сработал, но указанный (и приложенный) консольный загрузчик не нашёл файл, который должен бы сформироваться после первого этапа работы скрипта. Возможно дело в том, что что-то сменило само облако? Я знаю, что в инспекторе браузера на кнопке "скачать" нет никакой ссылки. Однако ссылка есть и прямая, с форматом (так я смотрел видео онлайн через своё приложение в телефоне)

**Comment by Geograph-us** [comment]
Исправил https://github.com/Geograph-us/Cloud-Mail.Ru-Downloader/releases/tag/1.0.1

**Comment by MiTereKun** [comment]
здорово, что так быстро поправили двухлетние файлы, вот только 
![default](https://user-images.githubusercontent.com/32958490/41720022-1926a25a-75a5-11e8-8821-96e683d423d8.png)
Я на самом деле не когда такие штуки не пробовал, скачал просто Denwer, выполнил инструкцию по установки сайта и скинул в директорию WWW файлы из архива. Перед этим качал язык php, он приложение hph.exe (ака CLI) включалось неактивной консолью, как к нему я не приделывал cloud@mail.ru_downloader.php - консоль либо нечего не делала, либо что-то быстро писала и закрывалась

**Comment by Geograph-us** [comment]
Лучше использовать php-cli в командной строке.
После установки php, скачайте целиком архив из релиза распакуйте в папку. В этой папке в адресной строке напишите:
`cmd`
откроется командная строка в ней надо написать:
`php -f cloud@mail.ru_downloader.php`
если напишет ошибку, что php не найден, нужно прописать путь к нему в PATH

**Comment by Geograph-us** [comment]
Хотя, если php в системе уже установлен, то после распаковки архива попробуйте просто запусить файл "cloud@mail.ru_downloader.php" двойным кликом в папке.
Важно, чтобы в папке лежали файлы aria2c.exe и links.txt с ссылками.

**Comment by MiTereKun** [comment]
![default](https://user-images.githubusercontent.com/32958490/41750504-b8028b64-75ff-11e8-89c2-2787397537b5.png)
![default](https://user-images.githubusercontent.com/32958490/41750562-17d36720-7600-11e8-94f7-ead15cbe37a7.png)

наброс файла на hph.exe - делал
![default](https://user-images.githubusercontent.com/32958490/41751696-14070d80-7606-11e8-81d1-15debc759ad5.png)

команду `php -f cloud@mail.ru_downloader.php` - вводил в адресную строку папки с hph, при добавленных файлах самого проекта

и даже cmd достал из папки систем 32, кинул в hph и выполнял команду `-f cloud@mail.ru_downloader.php` через этот cmd

- результат везде один и тот же, при уже заменённых ссылках в файле `links.txt` - ариа не может найти файл импут, который не создаётся не в одном из способов

- спасибо вам за потраченное время и инструкцию, но вы точно проверяли работоспособность после фикса? Возможно это из-за нового языка hph, по ссылке в описании вашего проекта уже нет той версии, на которой вы тестировали скрипт

**Comment by Geograph-us** [comment]
У Вас не настроенный php.
После того как скачали php с того сайта внутри есть файлы `php.ini-development` и `php.ini-production`.
Любой из них надо переименовать в `php.ini` и раскомментировать 2 строки:
`extension_dir = "ext"`
и
`extension=php_openssl.dll`

Видео-пример:
[![Cloud.MailRu.Downloader Video example](https://img.youtube.com/vi/WnJyXEdEqfI/0.jpg)](https://www.youtube.com/watch?v=WnJyXEdEqfI)

**Comment by MiTereKun** [comment]
Большое спасибо, вот теперь всё заработало и на какой гигантской скорости!!
Инструкция действительно не из лёгких, без видео и не понял бы. Это невероятно полезный инструмент, спасибо огромное!)
