### ISSUE TITLE
json_decode return null

### ISSUE THREAD

**Issue by LCZSQ** [Geograph-us/Cloud-Mail.Ru-Downloader#10]
function GetMainFolder($page)
  {
     if (preg_match('~"folder":\s+(\{.*"id":\s+"[^"]+"\s+\})~s', $page, $match)) {

        $res_json_dec = json_decode($match[1], true);

        // debug
        //file_put_contents(".debug\\debug_match[0].txt", $match[0]);
        //file_put_contents(".debug\\debug_match[1].txt", $match[1]);
        //var_dump($res_json_dec);

        if ($res_json_dec === NULL) {
           return GetMainFolder($match[1]);
        } else {
           return $res_json_dec;
        }
     } else {
        return false;
     }
  }

**Comment by Geograph-us** [comment]
Check new version
