### ISSUE TITLE
Не качает

### ISSUE THREAD

**Issue by SShirinyan** [Geograph-us/Cloud-Mail.Ru-Downloader#11]
Есть подозрение, что mail.ru у себя что-то поменял.
Start create input file for Aria2c Downloader...
Error https://cloud.mail.ru/public/2pzd/4a1EExvvb/
Can't find any fileДля продолжения нажмите любую клавишу . . .

**Comment by Geograph-us** [comment]
Странно у меня работает, попробуйте скачать заново скрипт, может быть старая версия?
![image](https://user-images.githubusercontent.com/7619691/93012932-a25f4c80-f5bd-11ea-9e79-059104d50921.png)

**Comment by SShirinyan** [comment]
Может с ссылками что-то криво? Можете у себя попробовать эту, к примеру https://cloud.mail.ru/public/2pzd/4a1EExvvb/ ?

**Comment by SShirinyan** [comment]
Версия с хаба. Вроде старых не находил. Качал час назад.

**Comment by Geograph-us** [comment]
ссылку как раз эту пробовал, на скриншоте это видно

**Comment by SShirinyan** [comment]
Да, действительно. А у вас php тот, который минимальный или отдельно ставили? Я, к сожалению, с этим языком не дружу, поэтому и отдэбажить ошибку не могу.

**Comment by SShirinyan** [comment]
Вроде нашел строку, на которой всё прерывается. 24) if($files = GetAllFiles($link))
Может у вас какие-то директории созданы или файлы, которых у меня нет?

**Comment by Geograph-us** [comment]
php тот же, папка "downloads" пустая рядом еще лежит

**Comment by MiTereKun** [comment]
> Есть подозрение, что mail.ru у себя что-то поменял.

аналогично, у меня тоже сломалось, когда я пробовал 27 августа. Пишет не может найти файл с прямыми ссылками (загрузка.txt), который действительно перестал создаваться

**Comment by SShirinyan** [comment]
Запустил под линухом. Поправил скрипт - вроде работает. Но нужна помощь специалистов. 
Ошибки:
`--2020-09-13 19:47:11--  https://cloclo2.cloud.mail.ru/public/2hqsv81s17u5SHFwWDGn/g/no/3LXr/2TfcqKinq/%5BBOOMINFO.RU%5D%20healmas.part2.rar
Connecting to cloclo2.cloud.mail.ru (cloclo2.cloud.mail.ru)|94.100.184.198|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://cloclo2.cldmail.ru/public/get/7YAHyodQEN1KuqhiDjy6BWdBU6sao7M1sACvpoSe5LGjKDdpGUHAcZPDQu4XP2iHnMVcuK/no/%5BBOOMINFO.RU%5D%20healmas.part2.rar [following]
--2020-09-13 19:47:11--  https://cloclo2.cldmail.ru/public/get/7YAHyodQEN1KuqhiDjy6BWdBU6sao7M1sACvpoSe5LGjKDdpGUHAcZPDQu4XP2iHnMVcuK/no/%5BBOOMINFO.RU%5D%20healmas.part2.rar
Connecting to cloclo2.cldmail.ru (cloclo2.cldmail.ru)|217.69.142.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1104475661 (1,0G) [application/octet-stream]
Saving to: ‘[BOOMINFO.RU] healmas.part2.rar’

[BOOMINFO.RU] healmas.part2.rar    100%[=============================================================>]   1,03G  6,65MB/s    in 2m 22s

2020-09-13 19:49:33 (7,43 MB/s) - ‘[BOOMINFO.RU] healmas.part2.rar’ saved [1104475661/1104475661]

Warning: wildcards not supported in HTTP.
--2020-09-13 19:49:33--  http://out=%5Bboominfo.xn--ru%5D%20%5B%20%5D%20%20-4yhbdawdzgnagc2bp2hkq1aga9bohmt9a93a9c/[BOOMINFO.RU]%20healmas.part2.rar
**Resolving out=[boominfo.xn--ru] [ ]  -4yhbdawdzgnagc2bp2hkq1aga9bohmt9a93a9c (out=[boominfo.xn--ru] [ ]  -4yhbdawdzgnagc2bp2hkq1aga9bohmt9a93a9c)... failed: Name or service not known.**
**wget: unable to resolve host address ‘out=[boominfo.xn--ru] [ ]  -4yhbdawdzgnagc2bp2hkq1aga9bohmt9a93a9c’
--2020-09-13 19:49:33--  http://dir=downloads/
Resolving dir=downloads (dir=downloads)... failed: Name or service not known.
wget: unable to resolve host address ‘dir=downloads’**
FINISHED --2020-09-13 19:49:33--
Total wall clock time: 5m 25s
Downloaded: 2 files, 2,2G in 5m 22s (7,01 MB/s)
Done!
`
**Сам файл сохраняется с апострофами. 
Хочется указать директорию для скачивания.**

Сам скрипт (глобально ничего не менял):
`<?php
        $links_file = "links.txt";
        $storage_path = "downloads";

        $file4aria = "input.txt";
        $aria2c = "/usr/bin/wget";
        $current_dir = dirname(__FILE__);

        // ======================================================================================================== //

        $file4aria = pathcombine($current_dir, $file4aria);
//      $aria2c = pathcombine($current_dir, $aria2c);

        if (file_exists($file4aria)) unlink($file4aria);
        $links = file($links_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

        echo "Start create input file for Aria2c Downloader..." . PHP_EOL;
        foreach($links as $link)
        {
                $link = trim($link);
                if(strpos($link, 'http') !== 0) continue;
                $base_url = "";
                $id = "";
                if($files = GetAllFiles($link))

                {
                        foreach ($files as $file)
                        {
                                $line = $file->download_link . PHP_EOL;
                                $line .= "      out=" . $file->output . PHP_EOL;
                                $line .= "      referer=" . $link . PHP_EOL;
                                $line .= "      dir=" . $storage_path . PHP_EOL;
                                file_put_contents($file4aria, $line, FILE_APPEND);
                        }
                        echo "Running Aria2c for download..." . PHP_EOL;
                        StartDownload();
                        @unlink($file4aria);
                }
                else
                {
                        die("Can't find any file");
                }
        }

        echo "Done!" . PHP_EOL;

        // ======================================================================================================== //

        class CMFile
        {
                public $name = "";
                public $output = "";
                public $link = "";
                public $download_link = "";

                function __construct($name, $output, $link, $download_link)
                {
                        $this->name = $name;
                        $this->output = $output;
                        $this->link = $link;
                        $this->download_link = $download_link;
                }
        }

        // ======================================================================================================== //

        function GetAllFiles($link, $folder = "")
        {
                global $base_url, $id;

                $page = get(pathcombine($link, $folder));
                if ($page === false) { echo "Error $link\r\n"; return false; }
                if (($mainfolder = GetMainFolder($page)) == false) { echo "Cannot get main folder $link\r\n"; return false; }

                if (!$base_url) $base_url = GetBaseUrl($page);
                if (!$id && preg_match('~\/public\/(.*)~', $link, $match)) $id = $match[1];

                $cmfiles = array();
                if ($mainfolder["name"] == "/") $mainfolder["name"] = "";
                foreach ($mainfolder["list"] as $item)
                {
                        if ($item["type"] == "folder")
                        {
                                $files_from_folder = GetAllFiles($link, pathcombine($folder, rawurlencode(basename($item["name"]))));

                                if (is_array($files_from_folder))
                                {
                                        foreach ($files_from_folder as $file)
                                        {
                                                if ($mainfolder["name"] != "")
                                                        $file->output = $mainfolder["name"] . "/" . $file->output;
                                        }
                                        $cmfiles = array_merge($cmfiles, $files_from_folder);
                                }
                        }
                        else
                        {
                                $fileurl = pathcombine($folder, rawurlencode($item["name"]));
                                // Старые ссылки содержат название файла в id
                                if (strpos($id, $fileurl) !== false) $fileurl = "";
                                $cmfiles[] = new CMFile($item["name"],
                                                                        pathcombine($mainfolder["name"], $item["name"]),
                                                                        pathcombine($link, $fileurl),
                                                                        pathcombine($base_url, $id, $fileurl));
                        }
                }

                return $cmfiles;
        }

        // ======================================================================================================== //

        function StartDownload()
        {
                global $aria2c, $file4aria;
                $command = "\"{$aria2c}\"  --continue --user-agent=\"Mozilla/5.0 (compatible; Firefox/3.6; Linux)\" --input-file=\"{$file4aria}\"";
                passthru("{$command}");
        }

        // ======================================================================================================== //

        function GetMainFolder($page)
        {
                if (preg_match('~"folder":\s+(\{.*?\}\s+\]\s+\})\s+\}~s', $page, $match))
                {
                        return json_decode($match[1], true);
                }
                else return false;
        }

        // ======================================================================================================== //

        function GetBaseUrl($page)
        {
                if (preg_match('~"weblink_get":.*?"url":\s*"(https:[^"]+)~s', $page, $match)) return $match[1];
                else return false;
        }

        // ======================================================================================================== //

        function get($url)
        {
                $proxy = null; //"127.0.0.1:8888";

                $http["method"] = "GET";
                if ($proxy) { $http["proxy"] = "tcp://" . $proxy; $http["request_fulluri"] = true; }
                $options['http'] = $http;
                $context = stream_context_create($options);
                $body = @file_get_contents($url, NULL, $context);
                return $body;
        }

        // ======================================================================================================== //

        function pathcombine()
        {
                $result = "";
                foreach (func_get_args() as $arg)
                {
                        if ($arg !== '')
                        {
                                if ($result && substr($result, -1) != "/") $result .= "/";
                                $result .= $arg;
                        }
                }
                return $result;
        }

        // ======================================================================================================== //
?>

`

**Comment by jekulyaa** [comment]
точно такая же проблема! вы решили как то?

**Comment by SShirinyan** [comment]
> точно такая же проблема! вы решили как то?

Да вроде работает. Через одно место, правда, но работает.

**Comment by jekulyaa** [comment]
> > точно такая же проблема! вы решили как то?
> 
> Да вроде работает. Через одно место, правда, но работает.

А что вы делали для решения этой проблемы?

**Comment by SShirinyan** [comment]
Не подскажу, но могу скинуть архив.

**Comment by jekulyaa** [comment]
> Не подскажу, но могу скинуть архив.

Давай

**Comment by jekulyaa** [comment]
> Не подскажу, но могу скинуть архив.

У тебя какая версия php?

**Comment by SShirinyan** [comment]
https://yadi.sk/d/MQsZtsWuUExzAQ
# php --version
PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct  7 2020 15:24:25) ( NTS )

**Comment by jekulyaa** [comment]
> PHP 7.2.24

mail.php переименовывать?

**Comment by jekulyaa** [comment]
> PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct 7 2020 15:24:25) ( NTS )

я маил.пхп переименовал, тоже самое

**Comment by jekulyaa** [comment]
> https://yadi.sk/d/MQsZtsWuUExzAQ
> 
> # php --version
> PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct 7 2020 15:24:25) ( NTS )

ты весь архив скинул? через что ты запускаешь?

**Comment by SShirinyan** [comment]
php mail.php
и он слизывает всё в эту же директорию

**Comment by jekulyaa** [comment]
> php mail.php
> и он слизывает всё в эту же директорию

Error https://cloud.mail.ru/public/5mAw/3E5WzUJsk/
Can't find any file

**Comment by jekulyaa** [comment]
> php mail.php
> и он слизывает всё в эту же директорию

помоги пожалуйста

**Comment by MiTereKun** [comment]
@SShirinyan `$aria2c = "/usr/bin/wget";` раз в оригинале был просто указатель на приложенный aria2c.exe - то видимо для этого пути предполагается наличие полного пакета php в системе? При изменении скрипта на ваш вариант - появляется понятная ошибка "the system cannot find the file specified". Так же я пробую с винды в самом простом CMD.

Я пользовался целых 2 года очень старой версией скрипта, ничего не менял, всё само по себе перестало работать этим летом. Попробовал последнюю сентябрьскую версию 1.0.4 - теперь файл inpud находиться, генерируется полная ссылка с разрешением файла, но не качается - Resource not found. Попробовал зайти в ту же секунду по полной ссылке - ответ 404. Очевидно опять что-то менялось на стороне самого сервиса.

**Comment by jekulyaa** [comment]
> @SShirinyan `$aria2c = "/usr/bin/wget";` раз в оригинале был просто указатель на приложенный aria2c.exe - то видимо для этого пути предполагается наличие полного пакета php в системе? При изменении скрипта на ваш вариант - появляется понятная ошибка "the system cannot find the file specified". Так же я пробую с винды в самом простом CMD.
> 
> Я пользовался целых 2 года очень старой версией скрипта, ничего не менял, всё само по себе перестало работать этим летом. Попробовал последнюю сентябрьскую версию 1.0.4 - теперь файл inpud находиться, генерируется полная ссылка с разрешением файла, но не качается - Resource not found. Попробовал зайти в ту же секунду по полной ссылке - ответ 404. Очевидно опять что-то менялось на стороне самого сервиса.

а что мне делать что бы оно работало

**Comment by MiTereKun** [comment]
**jekulyaa**, для начала не спамить сообщениями (здесь так не принято) и отвечать не через кнопку Quote reply (она только засоряет топик). Уведомления можно сделать через `@user` хотя и без неё **все** сообщения с issu приходят на почту.

Можете связаться с автором раздачи и попросить его использовать торрент или по истине резиновый файлообменник  https://gigafile.nu Или вы можете просто смотреть видео в браузере.
Сейчас данный скрипт для mail не работает с ошибкой Resource not found - очевидно происходит неправильная генерация прямой ссылки до файла. Очень вероятно, что это новая защита (а точнее её там раньше не было). Возможно **Geograph-us** обновит скрипт, а возможно разработчики облака теперь не хотят пускать пользователей в обход браузера и с этим ничего не сделать.
Кстати в приложении мега нз можно вставить чужую ссылку и всё скачать с неё, а у майла как и у яндекса - приложение работает только лично с твоим облаком и делегированными папками на твой аккаунт - не очень удобно и даже бесполезно

**Comment by jekulyaa** [comment]
Извините. Спасибо
