### ISSUE TITLE
ERROR: path too long

### ISSUE THREAD

**Issue by frizar** [Geograph-us/Cloud-Mail.Ru-Downloader#12]
Start create input file for Aria2c Downloader...
ERROR: path too long 264 > 260 chars: D:\Downloads\Cloud.Mail.Ru.Downloader/downloads/[pirat.biz] 2. Динамическая смена дня и ночи (2-ая версия)/[pirat.biz] Урок 2. Создание функций для получения информации о времени.mp4Для продолжения нажмите любую клавишу . . .

**Comment by Geograph-us** [comment]
Слишком длинный путь, должен быть не больше 260 символов (ограничение Windows).
Можно в скрипте поменять путь на папку "downloads" ближе к корню диска, например "D:\downloads" либо в самом облаке укоротить название папок

**Comment by frizar** [comment]
Я закомментил эту строчку с ошибкой и все норм скачалось. Странное ограничение какое-то, может же быть сколько угодно вложенных папок и длинна пути будет огромной.
Да и как-то же это все сохранилось в облаке, и с большой вероятностью было загружено туда с винды.

**Comment by Geograph-us** [comment]
Это ограничение в самой Windows идет из старых версий для совместимости, видимо оно у вас отключено, но чтобы не было непонятной ошибки скрипт проверяет длину пути

**Comment by Geograph-us** [comment]
Вот здесь человек жаловался на длинные пути https://www.youtube.com/watch?v=WnJyXEdEqfI&lc=Ugw6ahlmv-bw-Z6_3NF4AaABAg
