### ISSUE TITLE
Не могу скачать

### ISSUE THREAD

**Issue by jekulyaa** [Geograph-us/Cloud-Mail.Ru-Downloader#13]
Пишет Start create input file for Aria2c Downloader...
Error https://cloud.mail.ru/public/5mAw/3E5WzUJsk/
Can't find any fileДля продолжения нажмите любую клавишу . . .

**Comment by jekulyaa** [comment]
Пожалуйста, помогите, я не хочу качать 60 гб файлов через маил

**Comment by kactetus** [comment]
Проблема с **SSL routines:tls_process_server_certificate:certificate verify failed**

Решение функцию в **get** добавить
```
$options['ssl']=array(
			'verify_peer'=>false, 
			'verify_peer_name'=>false
		);
```

Должно получится так
```
function get($url)
	{
		$proxy = null; //"127.0.0.1:8888";
		$http["method"] = "GET";
		if ($proxy) { $http["proxy"] = "tcp://" . $proxy; $http["request_fulluri"] = true; }
		$options['http'] = $http;
		$options['ssl']=array(
			'verify_peer'=>false, 
			'verify_peer_name'=>false
		);
		$context = stream_context_create($options);
		$body = @file_get_contents($url, NULL, $context);
		return $body;
	}
```

**Comment by jekulyaa** [comment]
> Проблема с **SSL routines:tls_process_server_certificate:certificate verify failed**
> 
> Решение функцию в **get** добавить
> 
> ```
> $options['ssl']=array(
> 			'verify_peer'=>false, 
> 			'verify_peer_name'=>false
> 		);
> ```
> 
> Должно получится так
> 
> ```
> function get($url)
> 	{
> 		$proxy = null; //"127.0.0.1:8888";
> 		$http["method"] = "GET";
> 		if ($proxy) { $http["proxy"] = "tcp://" . $proxy; $http["request_fulluri"] = true; }
> 		$options['http'] = $http;
> 		$options['ssl']=array(
> 			'verify_peer'=>false, 
> 			'verify_peer_name'=>false
> 		);
> 		$context = stream_context_create($options);
> 		$body = @file_get_contents($url, NULL, $context);
> 		return $body;
> 	}
> ```

Ура! Работает, только вот теперь другая проблема...
Не скачивает из-за файла > 260 символов

**Comment by jekulyaa** [comment]
Разобрался, только вот проблема ещё одна. Я живу в Украине, mail ru заблокирован.
В php не разбираюсь, могу ли я купить забугорные прокси вида ip:login:pass и вставить? т.к бесплатные программы имеют ограниченные гб и много не скачаешь.
Если да, то как это сделать?

**Comment by kactetus** [comment]
строка $proxy = "127.0.0.1:8888"; указываешь прокси

**Comment by jekulyaa** [comment]
Ну, а если они приватные вида ip:login:pas, так же?

**Comment by DumbVibeCode** [comment]
Мда, похоже, у меня та же проблема. Как прописать логин и пароль?

**Comment by jekulyaa** [comment]
@kactetus Привет, сегодня решил скачать один файл, перестало работать, та же ошибка
