### ISSUE TITLE
Неактуальная проверка останавливает работу скрипта

### ISSUE THREAD

**Issue by sergeevichvn** [Geograph-us/Cloud-Mail.Ru-Downloader#14]
Доброе время суток, автору спасибо за скрипт и старания.
Сегодня получил такую ошибку:

`Start create input file for Aria2c Downloader...
ERROR: path too long 285 > 260 chars: {REPLACE} Для продолжения нажмите любую клавишу . . .`

Это связано с проверкой в коде (line:105):
`if (strlen($full_path) >= 260) die("ERROR: path too long " . strlen($full_path) . " > 260 chars: " . $full_path);`

Данную проблему решили в Windows 10, поэтому она не совсем актуальна.
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled = 1 (REG_DWORD)

@Geograph-us возможно, имеет смысл выводить предупреждение огромными буквами вместо остановки работы скрипта?! т.к. большинство пользователь не смогут самостоятельно решить проблему.

**Comment by kactetus** [comment]
Решение функцию в get добавить
$options['ssl']=array(
			'verify_peer'=>false, 
			'verify_peer_name'=>false
		);

Должно получится так
```
function get($url)
	{
		$proxy = null; //"127.0.0.1:8888";
		$http["method"] = "GET";
		if ($proxy) { $http["proxy"] = "tcp://" . $proxy; $http["request_fulluri"] = true; }
		$options['http'] = $http;
		$options['ssl']=array(
			'verify_peer'=>false, 
			'verify_peer_name'=>false
		);
		$context = stream_context_create($options);
		$body = @file_get_contents($url, NULL, $context);
		return $body;
	}
```
