### ISSUE TITLE
Формат ссылок у mail.ru поменялся

### ISSUE THREAD

**Issue by dimaninc2** [Geograph-us/Cloud-Mail.Ru-Downloader#15]
https://github.com/Geograph-us/Cloud-Mail.Ru-Downloader/blob/27229ed56c80433669c02c865ba01fc0e3596320/cloud%40mail.ru_downloader.php#L109

вот тут последний параметр лишний, с ним не работает
если оставить просто `pathcombine($base_url, $id)`, то работает хорошо

**Comment by TheWishMaster123123** [comment]
Все равно не работает.
