### ISSUE TITLE
Некоректная работа с большими каталогами

### ISSUE THREAD

**Issue by Vanger69** [Geograph-us/Cloud-Mail.Ru-Downloader#17]
При попытке скачать папки с облака содержащии большое количество папок, скрипт не отрабатывает. Если пробовать скачать подкаталоги меньшего объёма, то всё ок.

Версия - v1.0.6
Пример папки - https://cloud.mail.ru/public/4Yy2/5jeDWzmfz/

![image](https://user-images.githubusercontent.com/35919558/119111635-ebf51680-ba2b-11eb-9cdf-5999c09d294e.png)

**Comment by Geograph-us** [comment]
Да, 376 папок - скрипт не справляется, позже попробую поправить.
Пока, как вариант, можно в links.txt вручную добавить каждую папку:

```
https://cloud.mail.ru/public/4Yy2/5jeDWzmfz/0_ACloudGuru/a-practical-guide-to-amazon-eks/
https://cloud.mail.ru/public/4Yy2/5jeDWzmfz/0_ACloudGuru/advanced-networking-with-kubernetes-on-aws/
...
```

**Comment by Ali777666** [comment]
как я могу работат  этот скрипт google colab
ест здес jupiter блокнот вариант

**Comment by Geograph-us** [comment]
это php не python

**Comment by Ali777666** [comment]
есть какой-нибудь способ использовать Google Colab
Можете ли вы применить этот php к Google Colab?
