### ISSUE TITLE
aria2c.exe

### ISSUE THREAD

**Issue by mnqw95** [Geograph-us/Cloud-Mail.Ru-Downloader#2]
cloud@mail.ru_downloader.php создает input.txt ,запускает aria2c.exe, он стартует и тут же закрывается нечего не скачав  при этом удалая файл input.txt 
Если успеть сохранить input.txt  и запустить aria2c.exe из cmd с параметрам "aria2c -i input.txt" то он нормально начинает качать..
Еще сканирует  и сохраняет в  input.txt только первую ссылку на облако, остальные почему то игнорируются .

В php не разбираюсь, пожалуйста подправите кто нибудь код, ведь cloud@mail.ru_downloader крутая штука, автору респект )

**Comment by Geograph-us** [comment]
Всё делали как в этом видео?
[![Cloud.MailRu.Downloader Video example](https://img.youtube.com/vi/WnJyXEdEqfI/0.jpg)](https://www.youtube.com/watch?v=WnJyXEdEqfI)

**Comment by Geograph-us** [comment]
Чтобы файл Input.txt не удалялся можно удалить или закомментировать в php-файле эту строку:
`@unlink($file4aria);`

Но файл не должен удаляться до завершения работы aria2c

**Comment by Geograph-us** [comment]
Если обрабатывается только первая ссылка возможно в командной строке выводится какая-то ошибка при запуске?

**Comment by mnqw95** [comment]
Спасибо помогло с закрытием aria2c и теперь все ссылки из links.txt обрабатываются !!!!

**Comment by mnqw95** [comment]
Правда теперь придется в ручную удалять input.txt, но это уже не проблема
