### ISSUE TITLE
немного автоматизма

### ISSUE THREAD

**Issue by MiTereKun** [Geograph-us/Cloud-Mail.Ru-Downloader#3]
Для всех не разбирающихся можно было бы распространять скрипт с самим языком, в раскомментированном виде. Висит от не так уж и много, 60 МБ в распакованном виде.

Хочется, что бы вся эта гора файлов, вместе со скриптом, арией и импутом - оставалась в папке data, а в предыдущем каталоге только самое важное = линкс.txt, папка с готовыми файлами и запускатор start.bat

Первую часть задумки я нашёл как выполнить - код в start.bat
```
@echo off
cd data
php -f cloud@mail.ru_downloader.php
```
Теперь как сделать, что бы скрипт читал из предыдущей папки файл с ссылками и сохранял в ту же абстрактную папку готовые файлы?

**Comment by MiTereKun** [comment]
а, вот! Создать ярлыки папки downloads и файла links.txt а в свойстах удалить параметр "рабочая папка". Потестил - работает в разных местах, на разных дисках, здорово)
Единственное, что всё же имя папки менять нельзя, можно только месторасположение
![default](https://user-images.githubusercontent.com/32958490/41893178-32e5ed10-795e-11e8-8689-b68d9f64544c.png)

Нееет, блин, способ не работает ещё и при распаковке. Есть какой-нибудь стандартный заменитель ярлыков, быть может код (к примеру для ещё одного бад, да или даже того же) для подмены свойств ярлыков... Или это можно всё же решить атрибутом для php на указание %предыдущей директории%, сомнительно конечно, но было бы невероятно удобно

**Comment by Geograph-us** [comment]
Да, тоже подумывал включить php в состав и батник, который будет запускать скрипт или взять какой-нибудь php2exe, php-compiler, который делает примерно тоже самое.

**Comment by MiTereKun** [comment]
тогда смело заявляю, что из пака с языком можно выбросить всё, кроме следующих необходимых файлов (60 мб превратить в 8,65 МБ):
```
ssleay32.dll
php5ts.dll
libeay32.dll
php.exe
php.ini
ну и конечно папку ext с единственным файлом, который и нужно было расскоментировать - php_openssl.dll
```
да, такой язык не подойдёт уже ни для чего, но на самом деле, лично я, пытаясь сделать его частью среды операционки, столкнулся с проблемой. На [01:52 моменте из вашего виео](https://youtu.be/WnJyXEdEqfI?t=112) - у меня в списке применённых сред пользователя есть только  две переменных = TMP и TEMP и в обеих в графе Patch (из второй части окна) стоит язык джавы, а на кнопке изменить окно совсем не такое (виндовс 8.1) . Я уверен - есть 101-но процентное решение этой ситуации, но мне нужен php только для `cloud@mail.ru_downloader` + он же не будет конфликтовать с полным набором php в другом месте

### Пока вышло это  https://cloud.mail.ru/public/JFof/sYhwyAEvQ
____________________________________________________
Я был бы очень благодарен вам, если бы вы решили проблему с ярлыками на каталог downloads и фаил links.txt
[Есть команда для создания символьных ссылок](http://ab57.ru/cmdlist/mklink.html), есть атрибут для перехода в каталог возле исполняемого файла, как это соединить в один исполняемый фаел-то))


![default](https://user-images.githubusercontent.com/32958490/41914962-e8885ed0-7997-11e8-9354-06c549917d6d.png)

Кажется понял тупиковость ситуации. не буду вас путать, можете конечно и в истории редактирования посмотреть... Кажется что-то точно не так я делаю

всё работало бы, если бы не ограничение самой команды. И активированный от имини пользователя локальный CMD не помогает
В конечном итоге код должен бы быть следующий
```
@echo on
mklink /D "%cd%\data\links.txt" "%cd%\links.txt"
mklink /D "%cd%\data\downloads" "%cd%\downloads"
```

**Comment by Geograph-us** [comment]
Спасибо за помощь. Добавил минимальный php и bat-файл для простого запуска
https://github.com/Geograph-us/Cloud-Mail.Ru-Downloader/releases/tag/1.0.2

**Comment by MiTereKun** [comment]
Вам спасибо)

в самом конечном итоге код для создания ярлыков должен бы был быть всё же обратный 
```
@echo on
mklink /H "%cd%\links.txt" "%cd%\data\links.txt"
mklink /D "%cd%\downloads" "%cd%\data\downloads"
```
но максимум работает первая строчка, для второй нужен запуск от имени админа. Как бы я не крутился - это приводит лишь к тому, что атрибут %cd% (возле себя) - видится как директория  C:\Windows\system32

Вы пересобрали тоже не плохую версию, правда цветовая гамма арии убилась, ну да ладно, самое основное на самом главном месте

**Comment by MiTereKun** [comment]
![default](https://user-images.githubusercontent.com/32958490/41927591-fb8391e4-79b5-11e8-90cc-f45a86c680ba.png)![default](https://user-images.githubusercontent.com/32958490/41929487-8627d9cc-79bb-11e8-9b3a-ba423cbf0fd7.png)

**Comment by Geograph-us** [comment]
Странно, цвета должны были остаться. Специально для этого скачивал последнюю версию php 7.2.7
У меня в Win10 осталось с цветами.
А попробуйте в start.bat к строке, которая начинается с `"data\php\php.exe"` в конце добавить через пробел `--no-ansi`, а если не сработает то поменять её на `--ansi`:

`"data\php\php.exe" "data\cloud@mail.ru_downloader.php" --no-ansi`
или
`"data\php\php.exe" "data\cloud@mail.ru_downloader.php" --ansi`

**Comment by MiTereKun** [comment]
увы, не работает. 
А я довёл свой батник до консестенции гипер. Просто, не занимался раньше ничем подобным, мне понравилось)
https://cloud.mail.ru/public/Eddn/asasa3woA
