### ISSUE TITLE
Нет start.bat

### ISSUE THREAD

**Issue by mzf** [Geograph-us/Cloud-Mail.Ru-Downloader#5]
Нет start.bat в комплекте. Скрипт не работает

**Comment by Geograph-us** [comment]
Есть https://github.com/Geograph-us/Cloud-Mail.Ru-Downloader/releases

**Comment by mzf** [comment]
Все равно ничего не работает. Зачем такое выкладывать?

![image](https://user-images.githubusercontent.com/4039372/59920270-2a56b500-9454-11e9-9641-2fb54ddf5cdb.png)
