### ISSUE TITLE
How to download a single file from a folder containing many files ?

### ISSUE THREAD

**Issue by ghost** [Geograph-us/Cloud-Mail.Ru-Downloader#6]
When I'm trying to do that, it's downloading all the files, is there any way I can just download only a file from a folder in cloud mail which contains many files?
Thanks a lot.

**Comment by Geograph-us** [comment]
You can use web interface cloud.mail.ru for download single file from folder

**Comment by ghost** [comment]
I was wondering if it's possible with this tool, if possible, please provide an option for that. 
Thanks Anyway.

**Comment by MiTereKun** [comment]
create a folder (in your account) in the web version. Download the files you need into it. If they are on a different account, then the last element of the selected files sounds like “save to the cloud ~” - this is a transfer function to your cloud! Select the previously created folder in the list. Then from your account, open access to this folder. Place the resulting public link in the script to bypass the restriction when downloading the 4 GB archive and get the maximum speed

**Comment by MiTereKun** [comment]
to create a folder - you can see this good tutorial [youtu.be/5QZcOugHQ6s](https://www.youtube.com/watch?time_continue=63&v=5QZcOugHQ6s)

**Comment by svnkill** [comment]
не могу скачать

**Comment by Geograph-us** [comment]
@svnkill Попробуйте новое обновление https://github.com/Geograph-us/Cloud-Mail.Ru-Downloader/releases/tag/1.0.3
