### ISSUE TITLE
start.bat does not exists

### ISSUE THREAD

**Issue by sackett** [Geograph-us/Cloud-Mail.Ru-Downloader#8]
start.bat does not exists

**Comment by Geograph-us** [comment]
In release https://github.com/Geograph-us/Cloud-Mail.Ru-Downloader/releases

**Comment by sackett** [comment]
Already created by my own.
Script works fine! Thanks a lot!

P.S. --min-tls-version=TLSv1.2 with aria2c 1.35.0
