### ISSUE TITLE
input.txt doesn't exist

### ISSUE THREAD

**Issue by bodyajoy** [Geograph-us/Cloud-Mail.Ru-Downloader#9]
Got error message

Running Aria2c for download...
Exception caught
Exception: [download_helper.cc:563] errorCode=1 Failed to open the file F:\ownloader\data/input.txt, cause: File not found or it is a directory

tried to create file and then relaunch program, but it deletes file and can't open (or create it before) again

**Comment by Geograph-us** [comment]
You can try prevent the deleting input.txt file by commenting this line in the php-file:
`@unlink($file4aria);`

But the file should not be deleted until aria2c shutdown

**Comment by amplenus** [comment]
I have the same. This is full output

Start create input file for Aria2c Downloader...
PHP Warning:  Invalid argument supplied for foreach() in J:\CloudMailRu\data\cloud@mail.ru_downloader.php on line 75

Warning: Invalid argument supplied for foreach() in J:\CloudMailRu\data\cloud@mail.ru_downloader.php on line 75
Running Aria2c for download...
Exception caught
Exception: [download_helper.cc:563] errorCode=1 Failed to open the file J:\CloudMailRu\data/input.txt, cause: File not found or it is a directory

Done!

**Comment by d0ctorrus** [comment]
Подтверждаю, перестала работать win-версия и linux-версия. Похоже, что mailru поменяли дизайн страницы и теперь скрипт не может собрать прямые ссылки на файлы, спотыкается на первом шаге.

**Comment by iorsa** [comment]
You can try to replace GetMainFolder($page) function with this:

```
function GetMainFolder($page)
{
	if (preg_match('~"folder":\s+{.*?"list":.*?\}\s+\]~s', $page, $match))
	{
		$result = json_decode("{". $match[0] . "}}", true);
		$result = $result['folder'];
		return $result;
	}
	else return false;
}

```

**Comment by Geograph-us** [comment]
Try new update https://github.com/Geograph-us/Cloud-Mail.Ru-Downloader/releases/tag/1.0.3
